version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: crai_nginx
    restart: unless-stopped
    expose:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - crai_net

networks:
  crai_net:
    external: true
